name: CI
on: [push, workflow_dispatch]
jobs:
build:
runs-on: windows-latest
steps:
name: Download
run: Irivoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-ankl64.zip -OutFile ngrok.zip
name: Extract
run: Expand Archive ngrok.zip
name: Auth
run: \ngrok\ngrok.exe authtoken $Erv: NGROK_AUTH_TOKEN
env:
NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
name: Enable TS
run: Set ItemProperty Path "HKIM:\System\CurrentControlSet\Control\Terminal Server" name "fbenyTSConnections" Value e
run: Enable-NelFirewallRule DisplayGroup "Remote Desktop"
run: Set-ItemProperty -Path "IIKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
run: Set Localuser Name "runneradmin" Password (Convert To SecureString AsPlainText "P@ssuerd!" Force)
name: Create Tunnel
run: \ngrok\ngrok.exe tcp 3389
